// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
    "Header": {
        "filmoteka": "Filmoteka",
        "search": "Search",
        "home": "Home",
        "movies": "Movies",
        "tv": "TV Shows",
        "persons": "Persons"
    },
    "Home": {
        "1111111": "1111111111",
        "2222222": "2222222222",
        "3333333": "3333333333",
        "4444444": "4444444444"
    }
};
export default messages;