export const PARAMETERS = {
    API_KEY: process.env.NEXT_PUBLIC_API_KEY,
    BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    URL_IMG: process.env.NEXT_PUBLIC_URL_IMG,
    LOCALE: process.env.NEXT_PUBLIC_LOCALE,
    ADULT: process.env.NEXT_PUBLIC_ADULT,
};

export const IMG_SIZES = {
    MEDIA_CARD_COVER: 'w342',
    MEDIA_CARD_DETAILS_COVER: 'w500',
    MEDIA_CARD_DETAILS_BACKDROP: 'w1920_and_h800_multi_faces',
    SEASON_CARD_COVER: 'w185',
    SEASON_CARD_DETAILS_COVER: 'w342',
    EPISODE_CARD_COVER: 'w300',
    CAST_CARD_COVER: 'w185',
    CREATED_AVATAR: 'w45',
    REVIEWER_AVATAR: 'w185',
    COMPANY_LOGO: 'w92',
    NETWORK_LOGO: 'w92',
};