export const PARAMETERS = {
    API_KEY: process.env.NEXT_PUBLIC_API_KEY,
    BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    URL_IMG: process.env.NEXT_PUBLIC_URL_IMG,
    LOCALE: process.env.NEXT_PUBLIC_LOCALE,
    ADULT: process.env.NEXT_PUBLIC_ADULT,
};

export const IMG_SIZES = {
    MEDIA_CARD_COVER: 'w342',
    MEDIA_CARD_DETAILS_COVER: 'w500',
    MEDIA_CARD_DETAILS_BACKDROP: 'original',
    MEDIA_CARD_CURRENT_COVER: 'w92',
    SEASON_CARD_COVER: 'w154',
    SEASON_CARD_DETAILS_COVER: 'w92',
    EPISODE_CARD_COVER: 'w300',
    CAST_CARD_COVER: 'w180_and_h180_face',
    CREATOR_AVATAR: 'w50_and_h50_face',
    REVIEWER_AVATAR: 'w92',
    COMPANY_LOGO: 'w92',
    NETWORK_LOGO: 'w92',
    PERSON_CARD_COVER: 'h632',
    PERSON_CARD_DETAILS_COVER: 'h632',
    MEDIA_CAST_CARD_COVER: 'w92',
    MEDIA_CREW_CARD_COVER: 'w92',
};